<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>default</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>ArtiCluster.Applications.Cli.Tests</RootNamespace>
        <AssemblyName>ArtiCluster.Applications.Cli.Tests</AssemblyName>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <None Update="TestData\**\*">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="nunit" Version="4.5.1" />
        <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Commons\Tests.Helpers\Tests.Helpers.csproj" />
      <ProjectReference Include="..\Services\Applications.Services.csproj" />
    </ItemGroup>

</Project>
