<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <LangVersion>default</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <Copyright>R-Koubou</Copyright>
        <Company>R-Koubou</Company>
        <Product>ArtiCluster</Product>
        <AssemblyName>ArtiCluster.Applications.Cli</AssemblyName>
        <RootNamespace>ArtiCluster.Applications.Cli</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
      <PackageReference Include="Serilog" Version="4.3.1" />
      <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
      <PackageReference Include="System.CommandLine" Version="2.0.7" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Commons\Commons\Commons.csproj" />
      <ProjectReference Include="..\Services.Abstractions\Applications.Services.Abstractions.csproj" />
      <ProjectReference Include="..\Services\Applications.Services.csproj" />
    </ItemGroup>

</Project>
