<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>default</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <Copyright>R-Koubou</Copyright>
        <Company>R-Koubou</Company>
        <Product>ArtiCluster.Features.StudioOne.UseCases</Product>
        <AssemblyName>ArtiCluster.Features.StudioOne.KeySwitchDefinitions.UseCases</AssemblyName>
        <RootNamespace>ArtiCluster.Features.StudioOne.KeySwitchDefinitions.UseCases</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\Commons\Commons\Commons.csproj" />
      <ProjectReference Include="..\..\..\..\Shared\Shared.IO.Abstractions\Shared.IO.Abstractions.csproj" />
      <ProjectReference Include="..\..\..\..\Shared\Shared\Shared.csproj" />
      <ProjectReference Include="..\Gateways\StudioOne.KeySwitchDefinitions.Gateways.csproj" />
    </ItemGroup>

</Project>
