<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>default</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <Copyright>R-Koubou</Copyright>
        <Company>R-Koubou</Company>
        <Product>ArtiCluster.Features.Cubase15.ExpressionMaps.Facades</Product>
        <AssemblyName>ArtiCluster.Features.Cubase15.ExpressionMaps.Facades</AssemblyName>
        <RootNamespace>ArtiCluster.Features.Cubase15.ExpressionMaps.Facades</RootNamespace>
    </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Commons\Commons\Commons.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\Shared.IO.Abstractions\Shared.IO.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\Shared\Shared.csproj" />
    <ProjectReference Include="..\Contracts\Cubase15.ExpressionMaps.Contracts.csproj" />
    <ProjectReference Include="..\Exports\Cubase15.ExpressionMaps.Exports.csproj" />
  </ItemGroup>

</Project>
