<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>default</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <Copyright>R-Koubou</Copyright>
    <Company>R-Koubou</Company>
    <Product>ArtiCluster.Features.Cakewalk.ArticulationMaps.Contracts</Product>
    <AssemblyName>ArtiCluster.Features.Cakewalk.ArticulationMaps.Contracts</AssemblyName>
    <RootNamespace>ArtiCluster.Features.Cakewalk.ArticulationMaps.Contracts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Commons\Commons\Commons.csproj"/>
    <ProjectReference Include="..\..\..\..\Shared\Shared.IO.Abstractions\Shared.IO.Abstractions.csproj"/>
    <ProjectReference Include="..\..\..\..\Shared\Shared\Shared.csproj"/>
    <ProjectReference Include="..\Exports\Cakewalk.ArticulationMaps.Exports.csproj"/>
    <ProjectReference Include="..\Mappers\Cakewalk.ArticulationMaps.Mappers.csproj"/>
  </ItemGroup>

</Project>
