<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>default</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <Copyright>R-Koubou</Copyright>
    <Company>R-Koubou</Company>
    <Product>ArtiCluster.Applications.Services</Product>
    <AssemblyName>ArtiCluster.Applications.Services</AssemblyName>
    <RootNamespace>ArtiCluster.Applications.Services</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Commons\Commons\Commons.csproj"/>
    <ProjectReference Include="..\..\Features\Cakewalk\ArticulationMaps\Facades\Cakewalk.ArticulationMaps.Facades.csproj"/>
    <ProjectReference Include="..\..\Features\Cubase\ExpressionMaps\Facades\Cubase.ExpressionMaps.Facades.csproj" />
    <ProjectReference Include="..\..\Features\Logic\ArticulationSetDefinitions\Facades\Logic.ArticulationSetDefinitions.Facades.csproj"/>
    <ProjectReference Include="..\..\Features\StudioOne\KeySwitchDefinitions\Facades\StudioOne.KeySwitchDefinitions.Facades.csproj"/>
    <ProjectReference Include="..\..\Features\UniversalDefinitions\Facades\UniversalDefinitions.Facades.csproj"/>
    <ProjectReference Include="..\..\Shared\Shared.IO.Abstractions\Shared.IO.Abstractions.csproj"/>
    <ProjectReference Include="..\..\Shared\Shared\Shared.csproj"/>
    <ProjectReference Include="..\Services.Abstractions\Applications.Services.Abstractions.csproj"/>
  </ItemGroup>

</Project>