<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>default</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <Copyright>R-Koubou</Copyright>
        <Company>R-Koubou</Company>
        <Product>ArtiCluster.Features.Cubase.ExpressionMaps15.Imports</Product>
        <AssemblyName>ArtiCluster.Features.Cubase.ExpressionMaps15.Imports</AssemblyName>
        <RootNamespace>ArtiCluster.Features.Cubase.ExpressionMaps15.Imports</RootNamespace>
    </PropertyGroup>

</Project>