<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>default</LangVersion>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <Copyright>R-Koubou</Copyright>
        <Company>R-Koubou</Company>
        <Product>ArtiCluster.Features.Cubase.ExpressionMapDefinitions.Gateways</Product>
        <AssemblyName>ArtiCluster.Features.Cubase.ExpressionMapDefinitions.Gateways</AssemblyName>
        <RootNamespace>ArtiCluster.Features.Cubase.ExpressionMapDefinitions.Gateways</RootNamespace>
    </PropertyGroup>

</Project>