<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>default</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <Copyright>R-Koubou</Copyright>
        <Company>R-Koubou</Company>
        <Product>ArtiCluster.Features.UniversalDefinitionsNew.Exports</Product>
        <AssemblyName>ArtiCluster.Features.UniversalDefinitionsNew.Exports</AssemblyName>
        <RootNamespace>ArtiCluster.Features.UniversalDefinitionsNew.Exports</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="YamlDotNet" Version="17.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Commons\Commons\Commons.csproj" />
      <ProjectReference Include="..\..\..\Shared\Shared.IO.Abstractions\Shared.IO.Abstractions.csproj" />
      <ProjectReference Include="..\..\..\Shared\Shared\Shared.csproj" />
      <ProjectReference Include="..\Contracts\UniversalDefinitionsNew.Contracts.csproj" />
      <ProjectReference Include="..\Mappers\UniversalDefinitionsNew.Mappers.csproj" />
      <ProjectReference Include="..\Models\UniversalDefinitionsNew.Models.csproj" />
    </ItemGroup>

</Project>
