name: Build articluster-cli - Development

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - feature/**
      - fix/**
      - refactor/**

  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        default: '0.0.0-develop'

  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: '0.0.0-develop'

jobs:
  build-articluster-cli-development:
    uses: ./.github/workflows/build-csproj.yml
    secrets: inherit
    with:
      configuration: Debug
      prefix: articluster-cli
      base_dir: "articluster/Applications/Cli"
      csproject_filename: "Applications.Cli.csproj"
      version: ${{ inputs.version }}
