name: Build articluster-cli NuGet package (Pre-Release)

on:
  push:
    tags:
      - 'v*-pre'
      - 'v*-pre.*'

  workflow_dispatch:
    inputs:
      version:
        required: true
        default: ''

jobs:
  build-articluster-cli-nuget-pre-release:
    uses: ./.github/workflows/build-nuget-package.yml
    secrets: inherit
    with:
      configuration: Release
      pre_release: true
      prefix: articluster-cli-nuget
      base_dir: "articluster/Applications/Cli"
      csproject_filename: "Applications.Cli.csproj"
