name: Build articluster-cli - Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        default: '1.x.x'

  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: ''

jobs:
  build-articluster-cli-release:
    uses: ./.github/workflows/build-csproj.yml
    secrets: inherit
    with:
      configuration: Release
      prefix: articluster-cli
      base_dir: "articluster/Applications/Cli"
      csproject_filename: "Applications.Cli.csproj"
      version: ${{ inputs.version }}
