name: Build NuGet Package

on:
  workflow_call:
    inputs:
      prefix:
        required: true
        type: string
        description: |
          The prefix string to use for the artifact name.
      base_dir:
        required: true
        type: string
        description: |
          The base directory path of the .csproj file to build. (relative to repository root)
      csproject_filename:
        required: true
        type: string
        description: |
          The path to the .csproj file name to build.
      version:
        required: false
        type: string
        default: ""
        description: |
          Application version to set (e.g.: 1.2.3).
      configuration:
        required: true
        type: string
        default: "Debug"
        description: |
          dotnet Build configuration (Debug, Release)
      pre_release:
        required: false
        type: boolean
        default: false
        description: |
          If true, add option --prerelease to dotnet pack command to mark the package as pre-release.
      dotnet_custom_build_properties:
        required: false
        type: string
        default: ""
        description: |
          Additional properties to pass to dotnet pack command (e.g.: "-p:CustomProperty=Value -p:AnotherProperty=AnotherValue")

  workflow_dispatch:
    inputs:
      prefix:
        required: true
        type: string
        description: |
          The prefix string to use for the artifact name.
      base_dir:
        required: true
        type: string
        description: |
          The base directory path of the .csproj file to build. (relative to repository root)
      csproject_filename:
        required: true
        type: string
        description: |
          The path to the .csproj file name to build.
      version:
        required: false
        type: string
        default: ""
        description: |
          Application version to set (e.g.: 1.2.3).
      configuration:
        required: true
        type: choice
        options:
          - Debug
          - Release
        description: |
          dotnet Build configuration (Debug, Release)
      pre_release:
        required: false
        type: boolean
        default: false
        description: |
          If true, add option --prerelease to dotnet pack command to mark the package as pre-release.
      dotnet_custom_build_properties:
        required: false
        type: string
        default: ""
        description: |
          Additional properties to pass to dotnet pack command (e.g.: "-p:CustomProperty=Value -p:AnotherProperty=AnotherValue")

#--------------------------------------------------------------
# Build NuGet package
#--------------------------------------------------------------
jobs:
  build-nuget-package:
    name: build (${{ inputs.configuration }})
    runs-on: ubuntu-latest
    env:
      DOTNET_SDK_VERSION: ${{ vars.DOTNET_SDK_VERSION }}
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      PREFIX: ${{ inputs.prefix }}${{ inputs.pre_release && '-pre-release' || '' }}
      CSPROJ_FILENAME: ${{ inputs.csproject_filename }}
      BASE_DIR: ${{ github.workspace }}/${{ inputs.base_dir }}
      PUBLISH_DIRNAME: publish
      BUILD_CONFIGURATION: ${{ inputs.configuration }}
      DOTNET_CUSTOM_BUILD_PROPERTIES: ${{ inputs.dotnet_custom_build_properties }}
      PRE_RELEASE: ${{ inputs.pre_release }}
    steps:
    - name: Show workflow inputs
      run: |
        {
          echo "## Workflow Inputs"
          echo ""
          echo "|name|value|"
          echo "|----|-----|"
          echo "|ref| ${{ github.ref }}|"
          echo "|Commit SHA| ${{ github.sha }}|"
          echo "|Version|${{ inputs.version }}|"
          echo "|Configuration|${{ inputs.configuration }}|"
          echo "|Pre-Release|${{ inputs.pre_release }}|"
          echo "|Prefix|${{ inputs.prefix }}|"
          echo "|Base Directory|${{ inputs.base_dir }}|"
          echo "|csproj Filename|${{ inputs.csproject_filename }}|"
          echo "|Dotnet Custom Build Properties|${{ inputs.dotnet_custom_build_properties }}|"
          echo ""
        } >> $GITHUB_STEP_SUMMARY

    #----------------------------------------------------------
    # Guard - tag build must be Release Configuration
    #----------------------------------------------------------
    - name: Guard - tag build must be Release Configuration
      if: ${{ startsWith(github.ref, 'refs/tags/v') && inputs.configuration != 'Release' }}
      run: |
        echo "::error::Must use configuration=Release when building from tag/v*"
        exit 1

    #----------------------------------------------------------
    # Setup Environment Variables
    #----------------------------------------------------------
    - name: Sanitize Branch Name
      run: echo "BRANCH_NAME=$(echo ${{ github.ref_name }} | sed 's|/|-|g')" >> $GITHUB_ENV

    - name:  Setup csproj file path variable
      run: |
        echo "CSPROJ_PATH=${{ env.BASE_DIR }}/${{ env.CSPROJ_FILENAME }}" >> $GITHUB_ENV

    - name: Setup Nuget Pre-Release option variable
      run: |
        if [ "${{ env.PRE_RELEASE }}" = "true" ]; then
          echo "NUGET_PRERELEASE_OPTION=--prerelease" >> $GITHUB_ENV
        else
          echo "NUGET_PRERELEASE_OPTION=" >> $GITHUB_ENV
        fi

    - name: Setup Publish Directory Variable
      run: |
        echo "PUBLISH_DIR=${{ env.BASE_DIR }}/${{ env.PUBLISH_DIRNAME }}" >> $GITHUB_ENV
        echo "PUBLISH_RELATIVE_DIR_FROM_BASE=${{ env.PUBLISH_DIRNAME }}" >> $GITHUB_ENV

    - name: Setup Version Information Path Variable
      run: |
        echo "VERSION_INFO_PATH=${{ env.PUBLISH_DIR }}/VERSION.txt" >> $GITHUB_ENV

    #----------------------------------------------------------
    # Checkout repository
    #----------------------------------------------------------
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    #----------------------------------------------------------
    # Setup the application version
    #----------------------------------------------------------
    - name: "Setup the application version (If inputs.version is empty)"
      if: ${{ inputs.version == '' }}
      run: |
          echo "::info::The version value will be '0.0.0'"
          echo "BUILD_VERSION=0.0.0" >> $GITHUB_ENV

    - name: "Setup the application version (Use inputs.version)"
      if: ${{ inputs.version != '' }}
      run: |
        echo "::info::The version value will be overridden to '${{ inputs.version }}'"
        echo "BUILD_VERSION=${{ inputs.version }}" >> $GITHUB_ENV

    #----------------------------------------------------------
    # Setup the artifact name
    #----------------------------------------------------------
    - name: Setup the artifact name
      run: |
        echo "ARTIFACT_NAME=${{ env.PREFIX }}-${{ env.BUILD_CONFIGURATION }}-v${{ env.BUILD_VERSION }}-${{ inputs.configuration }}" >> $GITHUB_ENV

    - name: Show the artifact name
      run: |
        {
          echo "## Artifact Name"
          echo ""
          echo "${{ env.ARTIFACT_NAME }}"
        } >> $GITHUB_STEP_SUMMARY

    #----------------------------------------------------------
    # Show setup Environment Variables
    #----------------------------------------------------------
    - name: Show Environment Variables
      run: |
        {
          echo "## Environment Variables"
          echo ""
          echo "<details>"
          echo "<summary>Click to expand</summary>"
          echo ""
          echo "|name|value|"
          echo "|----|-----|"
          echo "|PREFIX|${{ env.PREFIX }}|"
          echo "|DOTNET_SDK_VERSION|${{ env.DOTNET_SDK_VERSION }}|"
          echo "|BASE_DIR|${{ env.BASE_DIR }}|"
          echo "|CSPROJ_PATH|${{ env.CSPROJ_PATH }}|"
          echo "|PUBLISH_DIR|${{ env.PUBLISH_DIR }}|"
          echo "|BUILD_CONFIGURATION|${{ env.BUILD_CONFIGURATION }}|"
          echo "|BUILD_VERSION|${{ env.BUILD_VERSION }}|"
          echo "|DOTNET_CUSTOM_BUILD_PROPERTIES|${{ env.DOTNET_CUSTOM_BUILD_PROPERTIES }}|"
          echo "|NUGET_PRERELEASE_OPTION|${{ env.NUGET_PRERELEASE_OPTION }}|"
          echo "|VERSION_INFO_PATH|${{ env.VERSION_INFO_PATH }}|"
          echo "|ARTIFACT_NAME|${{ env.ARTIFACT_NAME }}|"
          echo ""
          echo "</details>"
        } >> $GITHUB_STEP_SUMMARY


    #----------------------------------------------------------
    # Setup .NET SDK
    #----------------------------------------------------------
    - name: Install .NET SDK
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

    #----------------------------------------------------------
    # Show .csproj file
    #----------------------------------------------------------
    - name: Show .csproj file
      run: |
        {
          echo "## .csproj file content"
          echo ""
          echo "<details>"
          echo "<summary>Click to expand</summary>"
          echo ""
          echo "\`\`\`xml"
          cat ${{ env.CSPROJ_PATH }}
          echo "\`\`\`"
          echo ""
          echo "</details>"
          echo ""
        } >> $GITHUB_STEP_SUMMARY

    #----------------------------------------------------------
    # Create Version Information File
    #----------------------------------------------------------
    - name: Create Version information file
      run: |
        mkdir -p ${{ env.PUBLISH_DIR }}
        {
          echo "Build Configuration: ${{ env.BUILD_CONFIGURATION }}"
          echo "Build date: $(date)"
          echo "Version: ${{ env.BUILD_VERSION }}"
          echo "Pre-Release: ${{ env.PRE_RELEASE }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
        } >> ${{ env.VERSION_INFO_PATH }}

    #----------------------------------------------------------
    # Pack to NuGet package
    #----------------------------------------------------------
    - name: Create NuGet package
      run: |
        pushd ${{ env.BASE_DIR }}
        dotnet pack ${{ env.CSPROJ_PATH }} \
          -p:PackageVersion=${{ env.BUILD_VERSION }} \
          -p:FileVersion=${{ env.BUILD_VERSION }} \
          -p:Version=${{ env.BUILD_VERSION }} \
          -p:AssemblyVersion=${{ env.BUILD_VERSION }} \
          -c ${{ env.BUILD_CONFIGURATION }} \
          -o ${{ env.PUBLISH_RELATIVE_DIR_FROM_BASE }} \
          ${{ env.DOTNET_CUSTOM_BUILD_PROPERTIES }}
        popd

    - name: Show Version information file
      run: |
        {
          if [ -f ${{ env.VERSION_INFO_PATH }} ]; then
            echo "## Version Information File"
            echo ""
            echo "\`\`\`"
            cat ${{ env.VERSION_INFO_PATH }}
            echo ""
            echo "\`\`\`"
          fi
        } >> $GITHUB_STEP_SUMMARY

    #----------------------------------------------------------
    # Create Artifact
    #----------------------------------------------------------
    - name: Create Artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.BASE_DIR }}/${{ env.PUBLISH_DIRNAME }}
