name: NuGet articluster-cli - Development

on:
  push:
    branches:
      - develop

  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        default: '0.0.0-develop'

  workflow_call:
    inputs:
      version:
        required: true
        type: string
        default: '0.0.0-develop'

jobs:
  build-articluster-cli-nuget-development:
    uses: ./.github/workflows/pack-nuget.yml
    secrets: inherit
    with:
      configuration: Debug
      prefix: articluster-cli
      base_dir: "articluster/Applications/Cli"
      csproject_filename: "Applications.Cli.csproj"
      version: ${{ inputs.version }}
