name: NuGet articluster-cli - Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - release/**

  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        default: '1.x.x'

  workflow_call:
    inputs:
      version:
        required: true
        type: string
        default: '0.0.0-rc'

jobs:
  pack-nuget-articluster-cli-release:
    uses: ./.github/workflows/pack-nuget.yml
    secrets: inherit
    with:
      configuration: Release
      prefix: articluster-cli-nuget
      base_dir: "articluster/Applications/Cli"
      csproject_filename: "Applications.Cli.csproj"
      version: ${{ inputs.version }}
