name: NuGet articluster-cli - Development

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - feature/**
      - fix/**
      - refactor/**

  workflow_dispatch:

jobs:
  build-articluster-cli-nuget-development:
    uses: ./.github/workflows/pack-nuget.yml
    secrets: inherit
    with:
      configuration: Debug
      prefix: articluster-cli
      base_dir: "articluster/Applications/Cli"
      csproject_filename: "Applications.Cli.csproj"
