name: 'Unit Test - .NET projects'

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - hotfix/**
      - feature/**
      - refactor/**
      - fix/**

#--------------------------------------------------------------
# Run Unit Tests in solution
#--------------------------------------------------------------
jobs:
  run-dotnet-unit-test:
    name: Run .NET Unit Test
    runs-on: ubuntu-latest
    env:
      DOTNET_SDK_VERSION: ${{ vars.DOTNET_SDK_VERSION }}
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_UNIT_TEST_WORKING_DIRECTORY: ${{ vars.DOTNET_UNIT_TEST_WORKING_DIRECTORY }}

    steps:
      #----------------------------------------------------------
      # Checkout repository
      #----------------------------------------------------------
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      #----------------------------------------------------------
      # Show setup Environment Variables
      #----------------------------------------------------------
      - name: Show Environment Variables
        run: |
          {
            echo "## Environment Variables"
            echo ""
            echo ""
            echo "|name|value|"
            echo "|----|-----|"
            echo "|ref|${{ github.ref }}|"
            echo "|commit|${{ github.sha }}|"
            echo "|DOTNET_SDK_VERSION|${{ env.DOTNET_SDK_VERSION }}|"
            echo "|DOTNET_UNIT_TEST_WORKING_DIRECTORY|${{ env.DOTNET_UNIT_TEST_WORKING_DIRECTORY }}|"
            echo ""
          } >> $GITHUB_STEP_SUMMARY

      #----------------------------------------------------------
      # Setup .NET SDK
      #----------------------------------------------------------
      - name: Install .NET SDK
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      #----------------------------------------------------------
      # Run Unit Tests
      #----------------------------------------------------------
      - name: Run Unit Tests
        working-directory: ${{ env.DOTNET_UNIT_TEST_WORKING_DIRECTORY }}
        run: dotnet test
